# Builder
FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o server .

CMD ["./server"]

# Runner
FROM scratch

COPY --from=builder /app/server .

CMD [ "./server" ]